# Generated by Django 3.2.3 on 2021-07-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-id']},
        ),
    ]
