# Generated by Django 3.2.3 on 2021-07-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_created',
        ),
    ]
